Mvc5FuLuA/Mvc5FuLuA/Areas/LX01/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5FuLuA.Areas.LX01.Controllers
{
    public class DefaultController : Controller
    {
        // GET: LX01/Default
        public ActionResult Index()
        {
            String name = Request["UserName"];
            String pwd = Request["pwd"];
            ViewBag.Test = name + "  " + pwd;

            if (Request.IsAjaxRequest())
            {

                return PartialView();
            }
            else
                return View();
        }
    }
}

Mvc5FuLuA/Mvc5FuLuA/Areas/LX01/Controllers/NewController.cs
using Mvc5FuLuA.Areas.LX01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5FuLuA.Areas.LX01.Controllers
{
    public class NewController : Controller
    {
        // GET: LX01/New
        public ActionResult Index()
        {
            if (Request.IsAjaxRequest())
                return PartialView();
            else
                return View();
        }

        public ActionResult PartialFor(string id)
        {
            ViewBag.M = id;
            return PartialView();
        }

        public ActionResult FormControlDemo2(string id)
        {
            MyClass3Model c3 = new MyClass3Model();
            return PartialView(id, c3);
        }
    }
}

Mvc5FuLuA/Mvc5FuLuA/Areas/LX01/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mvc5FuLuA.Areas.LX01.Models.Essay;

namespace Mvc5FuLuA.Areas.LX01.Controllers
{
    public class TablesController : Controller
    {
        private Model1 db = new Model1();

        // GET: LX01/Tables
        public ActionResult Index()
        {
            if (Request.IsAjaxRequest())
                return PartialView(db.Table.ToList());
            else
                return View(db.Table.ToList());
        }

        // GET: LX01/Tables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Table.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (Request.IsAjaxRequest())
                {
                    return PartialView(table);
                }                 
                else
                    return View(table);
            }
        }

        // GET: LX01/Tables/Create
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
                return PartialView();
            else
                return View();
        }

        // POST: LX01/Tables/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Date,Content,Author,Views")] Table table)
        {
            if (ModelState.IsValid)
            {
                db.Table.Add(table);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                if (Request.IsAjaxRequest())
                    return PartialView(table);
                else
                    return View(table);
            }
        }

        // GET: LX01/Tables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Table.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (Request.IsAjaxRequest())
                    return PartialView(table);
                else
                    return View(table);
            }
        }

        // POST: LX01/Tables/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,Title,Date,Content,Author,Views")] Table table)
        {
            if (ModelState.IsValid)
            {
                db.Entry(table).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                if (Request.IsAjaxRequest())
                    return PartialView(table);
                else
                    return View(table);
            }
        }

        // GET: LX01/Tables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Table.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (Request.IsAjaxRequest())
                    return PartialView(table);
                else
                    return View(table);
            }
        }

        // POST: LX01/Tables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Table table = db.Table.Find(id);
            db.Table.Remove(table);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mvc5FuLuA/Mvc5FuLuA/Areas/LX01/Controllers/Test3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc5FuLuA.Areas.LX01.Models;

namespace Mvc5FuLuA.Areas.LX01.Controllers
{
    public class Test3Controller : Controller
    {
        // GET: LX01/Test3
        UserInfo user = new UserInfo()
        {
            UserName = "hr",
            UserPwd = "12345",
        };

        public ActionResult Index()
        {
            return PartialView(user);
        }

        // 服务端验证
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string userName)
        {
            ViewBag.Result = "验证失败。";
            if (this.ModelState.IsValid)
            {
                ViewBag.Result = "验证成功。";
            }
            return PartialView(user);
        }

        // 客户端验证
        public ActionResult Validation1(Staff student)
        {
            if (Request.HttpMethod == "GET")
            {
                student = new Staff
                {
                    UserName = "李",
                    UserPwd = "01"
                };
                return PartialView(student);
            }
            else
            {
                return JavaScript("alert('数据已提交！')");
            }
        }
    }
}

Mvc5FuLuA/Mvc5FuLuA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>

    @Styles.Render("~/Content/themes/base/jqueryui")
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/jquery-unobtrusive-ajax")
    @Scripts.Render("~/bundles/bootstrap")
</head>
@{
    var ajaxOptions = new AjaxOptions
    {
        LoadingElementId = "loading",
        UpdateTargetId = "mainWindow",
        OnFailure = "OnFailure"
    };
}
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("姓名：hhhh", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a>组号：01，上机位置：01排1号，学号：1812050074，性别：女</a></li>
                </ul>
                <ul id="loading" class="nav navbar-text navbar-right" style="display: none; color: white;">
                    <li>（正在加载，请稍等...）</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="row">
            <div class="col-md-3">
                <div class="leftMenu" style="margin-top:10px">
                    <h3 class="btn-success">实验内容</h3>
                    <div>
                        @Ajax.ActionLink("实验二—新增视图", "Index", "New", new { area = "LX01" }, ajaxOptions, new { @class = "list-group-item" })
                        @Ajax.ActionLink("实验二—新建模型", "FormControlDemo2", "New", new { area = "LX01"}, ajaxOptions, new { @class = "list-group-item" })
                        @Ajax.ActionLink("实验三—数据库操作", "Index", "Tables", new { area = "LX01" }, ajaxOptions, new { @class = "list-group-item" })
                        @Ajax.ActionLink("实验四—ViewBag", "Index", "Default", new { area = "LX01" }, ajaxOptions, new { @class = "list-group-item" })
                        @Ajax.ActionLink("实验四—服务端验证", "Index", "Test3", new { area = "LX01" }, ajaxOptions, new { @class = "list-group-item" })
                        @Ajax.ActionLink("实验四—客户端验证", "Validation1", "Test3", new { area = "LX01" }, ajaxOptions, new { @class = "list-group-item" })
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div id="mainWindow" style="border:1px solid blue;margin-top:10px; padding:10px; overflow-y:auto; overflow-x:hidden">
                    @RenderBody()
                </div>
            </div>
        </div>
        <footer style="margin-top:10px">
            <div class="btn-danger text-center">本组成员：hhhh（组长）、张三、李四、王五、赵六</div>
        </footer>
    </div>
    <script>
        $(document).ready(function () {
            var menu = $(".leftMenu");
            menu.accordion({ collapsible: true });
            $("#mainWindow").css({ minHeight: menu.height() });
        });
        function OnFailure(xhr) {
            $("body").html(xhr.responseText);
        }
    </script>
</body>
</html>