BooksStore/BooksStore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BooksStore.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();

        //添加
        public void AddItem(Books product, int quantity)
        {
            CartLine line = lineCollection.Where(p => p.books.Id == product.Id).FirstOrDefault();
            if (line == null)
            {
                lineCollection.Add(new CartLine() { books = product, Quantity = quantity });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        ////点击数量+号或点击数量-号或自己输入一个值
        //public void IncreaseOrDecreaseOne(Books product, int quantity)
        //{
        //    CartLine line = lineCollection.Where(p => p.Product.Id == product.Id).FirstOrDefault();
        //    if (line != null)
        //    {
        //        line.Quantity = quantity;
        //    }
        //}

        //移除
        public void RemoveLine(Books product)
        {
            lineCollection.RemoveAll(p => p.books.Id == product.Id);
        }

        //计算总价
        public decimal ComputeTotalPrice()
        {
            return lineCollection.Sum(p => (decimal)p.books.Price * p.Quantity);
        }


        //清空
        public void Clear()
        {
            lineCollection.Clear();
        }

        //获取
        public IEnumerable<CartLine> Lines
        {
            get { return lineCollection; }
        }

        public class CartLine
        {
            public Books books { get; set; }
            public int Quantity { get; set; }
        }

    }
}

BooksStore/BooksStore/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BooksStore.Models;

namespace BooksStore.Controllers
{
    public class BooksController : Controller
    {
        private BookModel db = new BookModel();

        // GET: Books
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        public ActionResult Test()
        {
            return View(db.Books.ToList());
        }

        public ActionResult Search(string search)
        {
            ViewBag.search = search;
            var t = db.Books.ToList();
            if (string.IsNullOrEmpty(search) == false)
                t = t.Where(item => item.Name.Contains(search)).ToList();
            return View(t);
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Price,Category")] Books books)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(books);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(books);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: Books/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Price,Category")] Books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(books);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Books books = db.Books.Find(id);
            db.Books.Remove(books);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        string Cate;
        public ActionResult Computer()
        {
            Cate = "Computer";
            var list = from c in db.Books where c.Category == Cate select c;
            return View(list);
        }

        public ActionResult Digital()
        {
            string Cate = "Digital";
            var list = from c in db.Books where c.Category == Cate select c;
            return View(list);
        }

        public ActionResult Industry()
        {
            string Cate = "Industry";
            var list = from c in db.Books where c.Category == Cate select c;
            return View(list);
        }

        public ActionResult Manage()
        {
            string Cate = "Manage";
            var list = from c in db.Books where c.Category == Cate select c;
            return View(list);
        }

        public ActionResult Psychology()
        {
            string Cate = "Psychology";
            var list = from c in db.Books where c.Category == Cate select c;
            return View(list);
        }

        public ActionResult Textbook()
        {
            string Cate = "Textbook";
            var list = from c in db.Books where c.Category == Cate select c;
            return View(list);
        }
    }
}

BooksStore/BooksStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BooksStore.Models;

namespace BooksStore.Controllers
{
    public class CartController : Controller
    {
        public ActionResult CartIndex(Cart cart, string returnUrl)
        {
            return View(new CartIndexVm
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        //添加到购物车
        public ActionResult AddToCart(Cart cart, int id, string returnUrl)
        {
            Books product = GetAllProducts().Where(p => p.Id == id).FirstOrDefault();
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("CartIndex", new { returnUrl });
            //return View();
        }

        ////点击数量+号或点击数量-号或自己输入一个值
        //[HttpPost]
        //public ActionResult IncreaseOrDecreaseOne(Cart cart, int id, int quantity)
        //{
        //    Books product = GetAllProducts().Where(p => p.Id == id).FirstOrDefault();
        //    if (product != null)
        //    {
        //        cart.IncreaseOrDecreaseOne(product, quantity);
        //    }
        //    return Json(new
        //    {
        //        msg = true
        //    });
        //    //return RedirectToAction("CartIndex");
        //}

        //从购物车移除
        public ActionResult RemoveFromCart(Cart cart, int id, string returnUrl)
        {
            Books product = GetAllProducts().Where(p => p.Id == id).FirstOrDefault();
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("CartIndex", new { returnUrl });
        }

        //清空购物车
        public ActionResult EmptyCart(Cart cart, string returnUrl)
        {
            cart.Clear();
            return View("Index", new ProductsListVm { Products = GetAllProducts() });
        }

        //显示购物车摘要
        public ActionResult Summary(Cart cart)
        {
            return View(cart);
        }

        private BookModel db = new BookModel();
        private List<Books> GetAllProducts()
        {
            return db.Books.ToList();
        }
    }
}

BooksStore/BooksStore/Views/Cart/CartIndex.cshtml
@model BooksStore.Models.CartIndexVm
@{
    ViewBag.Title = "Your Cart";
    Layout = null;
    int number = Model.Cart.Lines.Count();
    decimal money = Model.Cart.ComputeTotalPrice();
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Login</title>
    <link href="~/LocalStyle/CSS/footer.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    

</head>
<body style="padding:0; margin:0">
    @RenderPage("~/Views/Shared/_AccHead.cshtml")
    <div id="none_goods" class="cart_box mainWidth mCenter">
        <div class="flow_step">
            <ul>
                <li>1.我的购物车</li>
                <li>2.确认订单信息</li>
                <li>3.成功提交订单</li>
            </ul>
        </div>
        <div class="flow_strp_title">
            <h2><strong>购物车</strong></h2>
            <label class="fLeft"></label>
        </div>
        <div class="flow_pro">
            <table id="tb" cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr>
                        <th width="5%"></th>
                        <th width="25%">商品</th>
                        <th width="10%">类型</th>
                        <th width="10%">价格</th>
                        <th width="10%">数量</th>
                        <th width="10%">价格</th>
                        <th width="10%">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="8">
                            <div class="flow_cart">
                                <p>您的购物车没有商品</p>
                                @Html.ActionLink("现在就去选购吧！", "Index", "Home")
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="goon_buy fRight">@Html.ActionLink(" ", "Computer", "Books")</div>
    </div>
    <div id="have_goods" class="cart_box mainWidth mCenter">
        <div class="flow_step">
            <ul>
                <li>1.我的购物车</li>
                <li>2.确认订单信息</li>
                <li>3.成功提交订单</li>
            </ul>
        </div>
        <div class="flow_strp_title">
            <h2><strong>购物车</strong></h2>
            <label class="fLeft"></label>
        </div>
        <div class="flow_pro">
            <table id="tb" cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr>
                        <th width="5%"></th>
                        <th width="25%">商品</th>
                        <th width="10%">类型</th>
                        <th width="10%">价格</th>
                        <th width="10%">数量</th>
                        <th width="10%">价格</th>
                        <th width="10%">操作</th>
                    </tr>
                </thead>
                <tbody class="have_goods">
                    @foreach (var line in Model.Cart.Lines)
                    {

                        <tr>
                            <td></td>
                            <td>@line.books.Name</td>
                            <td>@line.books.Category</td>
                            <td>@line.books.Price.ToString()</td>
                            <td>@line.Quantity</td>
                            <td>@((line.Quantity * line.books.Price).ToString())</td>
                            <td>
                                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                                {
                                    @Html.Hidden("Id", line.books.Id)
                                    @Html.HiddenFor(x => x.ReturnUrl)
                                    <input class="delete" style="border:none;background-color:white" type="submit" value="删除" />
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="goon_buy fRight">
            @Html.ActionLink(" ", "Computer", "Books")
            <input id="alert_confirm" type="button" onclick="ConfirmOrder()" class="confirm_order" value="确认订单" />
        </div>
        <div class="sum_price">
            <span>Total:</span>
            <span style="color:red">
                @Model.Cart.ComputeTotalPrice().ToString("c")
            </span>
        </div>
        <div id="pay_money" class="mainWidth mCenter">
            <div id="timer" style="color:red;"></div>
            <div id="warring" style="color:red;"></div>
            <h3>结算：￥@money</h3>
            <img width="180" src="~/Image/qr.png" />
        </div>
    </div>    
    <script>
        window.onload = function () {
            if (@number == 0) {
                document.getElementById('none_goods').style.display = "block";
                document.getElementById('have_goods').style.display = "none";
            } else {
                document.getElementById('none_goods').style.display = "none";
                document.getElementById('have_goods').style.display = "block";
            }
        };

               
        function ConfirmOrder() {
            alert('20秒后订单关闭');
            document.getElementById('pay_money').style.display = "block";
        }

        var maxtime = 20;
        function CountDown() {
            if (maxtime >= 0) {
                minutes = Math.floor(maxtime / 60);
                seconds = Math.floor(maxtime % 60);
                msg = "订单取消还有" + minutes + "分" + seconds + "秒";
                document.all["timer"].innerHTML = msg;
                if (maxtime == 5 * 60) alert("还剩5分钟");
                --maxtime;
            } else {
                clearInterval(timer);
                document.getElementById('pay_money').style.display = "none";
                var Response = prompt("亲，您对本次购物满意吗？", "满意");
                console.log(Response);
                document.getElementById('none_goods').style.display = "block";
                document.getElementById('have_goods').style.display = "none";
            }
        }
        timer = setInterval("CountDown()", 1000);
    </script>
</body>
</html>




    

BooksStore/BooksStore/Views/Cart/Summary.cshtml
@model BooksStore.Models.Cart
<div id="cart">
    <span class="caption">
        <b>Your cart:</b>
        @Model.Lines.Sum(x => x.Quantity) item(s),
        @Model.ComputeTotalPrice().ToString("c")
    </span>
    @Html.ActionLink("Checkout", "CartIndex", "Cart",new { returnUrl = Request.Url.PathAndQuery }, null)
</div>